---
- hosts: default
  tasks:
  - name: Install tmux (Debian)
    apt: name=tmux state=present
    when: ansible_os_family == "Debian"
    register: tmux_installed
    become: yes
    become_user: root
  - name: Install tmux (RedHat)
    dnf: name=tmux state=present
    when: ansible_os_family == "RedHat"
    register: tmux_installed
    become: yes
    become_user: root
